#! /usr/bin/env perl
use strict;
use Data::Dumper;
use Time::HiRes 'gettimeofday';
use GenomeTypeObject;
use File::Temp;
use Getopt::Long::Descriptive;
use File::Copy;
use IPC::Run qw(run);
use Cwd;

# Try to load version module; fall back to "dev" if not available
my $tool_version;
eval {
    require LowVanVersion;
    $tool_version = LowVanVersion::get_version();
};
if ($@ || !$tool_version) {
    $tool_version = "dev";
}

my $default_data_dir = $ENV{LOWVAN_DATA_DIR} // "/home/jjdavis/bin/Viral_Annotation";

my($opt, $usage) = describe_options("%c %o",
				    ["input|i=s"       => "Input file"],
				    ["output|o=s"      => "Output file"],
				    ["prefix|x=s"      => "File Prefix", { default => "Viral_Anno" }],
				    ["remove-existing" => "Remove existing CDS, mat_peptide, and RNA features if run is successful"],	
				    ["threads|t=i"     => "Limit to this many threads", { default => 8 }],
				    ["debug|d"         => "Enable debugging"],
				    ["cdir|c=s"        => "Full path to reference contigs directory", {default => "$default_data_dir/Viral-Rep-Contigs"}],
				    ["pdir|p=s"        => "Full path to the PSSM directory", {default => "$default_data_dir/Viral-PSSMs"}],
				    ["json|j=s"        => "Full path to the JSON opts file", {default => "$default_data_dir/Viral_PSSM.json"}],
				    ["max|a=i"         => "Max contig length, default is 40000", { default => 40000 }],
				    ["min|z=i"         => "Min contig length, default is 300", { default => 300 }],
				    ["viral-taxon=s"   => "Declare the annotation taxon instead of detecting it by BLASTn. See --list-viral-taxa. Also sets viral_family, which selects the Transcript-Editing/ and Splice-Variants/ dirs used by the downstream steps"],
				    ["list-viral-taxa" => "List the valid --viral-taxon values and exit"],
				    ["skip-classification" => "With --viral-taxon, BLASTn only that taxon reference contigs (1-14) instead of every reference contig. Much faster, but no cross-check against the other taxa, so a wrong --viral-taxon will not be caught. For bulk reruns where the taxon is already known to be correct"],
				    ["margin=f"        => "Minimum ratio between the winning and runner-up taxon bit scores, e.g. --margin 1.3. Off by default. Warns when the classification is a near-tie and records the margin on the GTO close_genomes record; never rejects. Incompatible with --skip-classification, which searches one taxon only"],
				    ["version|v"       => "Show version information"],
				    ["help|h"          => "Show this help message"]);

if ($opt->version) {
    print "annotate_by_viral_pssm-GTO.pl version $tool_version\n";
    exit 0;
}
print($usage->text), exit 0 if $opt->help;

# Delegate to the base script rather than reimplementing, so there is one canonical list.
# Must run before create_from_file() below, which requires -i.
if ($opt->list_viral_taxa) {
    my $listed = run(["annotate_by_viral_pssm.pl", "-list-vtax",
		      "-pssm", $opt->pdir, "-j", $opt->json]);
    exit($listed ? 0 : 1);
}

die($usage->text) if @ARGV != 0;

chomp(my $hostname = `hostname`);

my $tempdir = File::Temp->newdir(CLEANUP => ($opt->debug ? 0 : 1));
my $prefix = $opt->prefix // "Viral_Anno";

print STDERR "Tempdir=$tempdir\n" if $opt->debug;

my $here = getcwd;

my $genome_in = GenomeTypeObject->create_from_file($opt->input);
$genome_in or die "Error reading and parsing input";



#
# Invoke annotate_by_viral_pssm.pl to annotate viral genome.
#
# We parse the feature table file that is generated by annotate_by_viral_pssm.pl. It contains three feature types.
# CDS, RNA, and mat_peptide
# It returns a GTO to stdout
#

my $sequences_file = $genome_in->extract_contig_sequences_to_temp_file();
my $taxon_id       = $genome_in->{ncbi_taxonomy_id};   #I should be able to get rid of this if I don't require it in the base-script
my $name           = $genome_in->{scientific_name};        #I should also be able to get rid of this 

if (! $sequences_file){die "No sequences in the input GTO\n";}
if (! $taxon_id)      {die "No NCBI taxonomy ID in the input GTO\n";}
if (! $name)          {die "No genome name in the input GTO\n";}

my @params = ("-i",    $sequences_file,
		      "-t",    "$tempdir",
		      "-p",    $prefix,
		      "-tax",  $taxon_id,
		      "-g",    $name,
		      "-threads", $opt->threads,
		      "-c",    $opt->cdir,
		      "-pssm", $opt->pdir,
		      "-j",    $opt->json,
		      "-min",  $opt->min,
		      "-max",  $opt->max,
		      "-s",
		      "-no",
		      "-tbl",
		      "-tmp");

push @params, ("-vtax", $opt->viral_taxon) if $opt->viral_taxon;
push @params, ("-skip-classification")             if $opt->skip_classification;
push @params, ("-margin", $opt->margin)            if $opt->margin;

print STDERR Dumper(\@params);
my $ok = run(["annotate_by_viral_pssm.pl", @params], ">", "$here/$prefix.stdout.txt", "2>", "$here/$prefix.stderr.txt");


if (!$ok)
{
    print STDERR "Viral Annotation run failed with rc=$?. Stderr:\n";
    copy("$here/$prefix.stderr.txt", \*STDERR);   # was hardcoded Viral_Anno.stderr.txt + mislabeled "Stdout" (gist #17)
    # NOTE: execution continues below and still writes an output GTO. See caveat in the porting notes --
    # a genuine BLAST crash and the base script's graceful "no reference match" exit(1) are
    # indistinguishable by return code, so we do not hard-abort here.
    # (Exception: under --viral-taxon the base script warns instead of exiting on a low -mcb,
    # so a non-zero rc there is unambiguously a real failure.)
}


    
my $event = {
    tool_name => "LowVan Annotate",
    tool_version => $tool_version,
    execution_time => scalar gettimeofday,
    parameters => \@params,
};

my $event_id = $genome_in->add_analysis_event($event);


## Parse the generated peptide file. We collect the CDS, mature_peptides, and RNAs then
## add features so that we can register the counts.
##

my $viral_family;

my ($close_bit, $close_id, $close_name, $close_file);
if (open(my $tbl, "<", "$here/$prefix.stdout.txt"))
{
	my %features;
	while (<$tbl>)
	{
		chomp;
		my ($local_genome_id, $name, $contig, $anno_source, $type, $local_peg_id, $symbol, $start, $stop, $strand, $len, $virus, $cf, $cb, $ci, $cn, $pssm, $anno, $dna, $aa) = split /\t/; 
		$close_file = $cf;
		$close_bit  = $cb;
		$close_id   = $ci;
		$close_name = $cn;

		$viral_family = $virus;
		
		my $feature;
		if ($type =~ /(mat_peptide)|(CDS)/)
		{
			my $pssm_id = $pssm;
			$pssm_id =~ s/\.pssm$//;  # Remove .pssm suffix for family_assignments
			$feature =
			{
				type        => $type,
				contig      => $contig,
				aa_sequence => $aa,
				location    => ([[$contig, $start, $strand, $len]]),
				product     => $anno,
				pssm        => ([["LOWVAN", $pssm_id, $anno, "LowVan Annotate $tool_version"]]),
				symbol      => $symbol,
			}
		}
		elsif ($type =~ /RNA/)
		{
			$feature =
			{ 
				type        => $type,
				contig      => $contig,
				location    => ([[$contig, $start, $strand, $len]]),
				product     => $anno,
				symbol      => $symbol,
			}
		}		
		push(@{$features{$type}}, $feature);
	}
	
    if (%features && $opt->remove_existing)
    {
		my @to_del = $genome_in->fids_of_type('CDS', 'mat_peptide', 'RNA');
		print STDERR "Delete @to_del\n";
		$genome_in->delete_feature($_) foreach @to_del;
    }

    
    for my $type (sort keys %features)   # sort: deterministic new_feature_id assignment across runs (gist #19)
    {
		my $feats = $features{$type};
		my $n = @$feats;
		my $id_type = $type;
	
		for my $feature (@$feats)
		{
			my $p = {
					-id	                 => $genome_in->new_feature_id($id_type),
					-type 	             => $type,
					-location 	         => $feature->{location},
					-analysis_event_id 	 => $event_id,
					-annotator           => 'LowVan Annotate',
					#-alias_pairs         => [[gene => $feature->{symbol}]],
					-protein_translation => $feature->{aa_sequence},
					-function            => $feature->{product},
					-family_assignments  => $feature->{pssm},
					};
			
			if (defined $feature->{symbol} && $feature->{symbol} ne '') 
			{
				$p->{-alias_pairs} = [[gene => $feature->{symbol}]];
   			}
			$genome_in->add_feature($p);
		}
    }

	#add close genome:
	#$close_genome, $close_bit, $close_id, $close_name,
	# An empty feature table leaves all of these undef -- do not append a record of nulls.
	# Much more likely now that --viral-taxon can name a taxon whose PSSMs match nothing.
	if (defined $close_id)
	{
		my $close = { genome_id => $close_id, genome_name => $close_name, file_name => $close_file, closeness_measure => "BLASTn bit score", closeness_value => $close_bit, analysis_method => "LowVan Annotate"};

		# --margin: carry the confidence of the classification, not just its strength.
		# The base script wrote these to $prefix.classification; absent that file the
		# flag was not used and the record keeps its original shape.
		if (my $cls = read_classification("$here/$prefix.classification"))
		{
			$close->{margin}          = $cls->{margin}        if defined $cls->{margin};
			$close->{runner_up}       = $cls->{runner_up}     if defined $cls->{runner_up};
			$close->{runner_up_value} = $cls->{runner_up_bit} if defined $cls->{runner_up_bit};
			$close->{margin_below_threshold} = $cls->{below_threshold}
				if defined $cls->{below_threshold};
		}
		push(@{$genome_in->{close_genomes}}, $close);
	}

	# Fall back to the declared taxon: without this, a --viral-taxon run that calls zero
	# features leaves viral_family undef and every downstream step dies on its "$fam or die".
	$genome_in->{viral_family} = defined $viral_family ? $viral_family : $opt->viral_taxon;
}
else
{
    warn "Could not read $here/$prefix.stdout.txt\n";
}

$genome_in->destroy_to_file($opt->output);

#
# Read the <prefix>.classification sidecar written by annotate_by_viral_pssm.pl -margin.
# Returns undef when the file is absent, i.e. when --margin was not used -- that is the
# normal case and must not warn.  Format is one tab-separated key/value per line, plus
# repeated "score" lines holding the full per-taxon ranking, which we do not need here.
#
sub read_classification
{
	my($file) = @_;
	return undef unless -s $file;

	open(my $fh, "<", $file) or do { warn "Could not read $file: $!\n"; return undef; };
	my %cls;
	while (<$fh>)
	{
		chomp;
		my($key, @val) = split /\t/;
		next if $key eq "score";
		$cls{$key} = $val[0];
	}
	close $fh;

	# "inf" means nothing else was in contention; leave margin unset rather than
	# putting a non-numeric value into the GTO.
	delete $cls{margin} if defined $cls{margin} && $cls{margin} !~ /^[\d.]+$/;
	$cls{margin} += 0            if defined $cls{margin};
	$cls{runner_up_bit} += 0     if defined $cls{runner_up_bit};
	$cls{below_threshold} += 0   if defined $cls{below_threshold};
	delete $cls{runner_up} if defined $cls{runner_up} && $cls{runner_up} eq "-";
	return \%cls;
}




